{{- if .Values.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  S3_BUCKET_NAME: {{ quote .Values.s3.bucketName }}
  S3_ACCESS_KEY_ID: {{ quote .Values.s3.accessKeyId }}
  S3_SECRET_KEY: {{ quote .Values.s3.secretKey }}
  S3_SERVER: {{ quote .Values.s3.server }}
  S3_SERVER_PORT: {{ quote .Values.s3.serverPort }}
  S3_SERVER_PROTO: {{ quote .Values.s3.serverProto }}
  S3_REGION: {{ quote .Values.s3.region }}
  S3_STYLE: {{ quote .Values.s3.style }}
  S3_DEBUG: {{ quote .Values.s3.debug }}
  AWS_SIGS_VERSION: {{ quote .Values.aws.sigsVersion }}
  ALLOW_DIRECTORY_LIST: {{ quote .Values.global.allowDirectoryList }}

{{- end }}
