apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod 
  template:
    metadata:
      labels:
        podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod
      annotations:
      {{- range $key, $val := .Values.deployment.pod.annotations }}
        {{ $key }}: {{ tpl $val $ | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-container
          image: {{ .Values.image }}
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
        {{- if .Values.authentication.opa.enabled }}
        {{- template "nginx-s3-gateway.envoy-container" . }}
        {{- template "nginx-s3-gateway.opa-container" . }}
        {{- end}}
      volumes:
      {{- if .Values.authentication.opa.enabled }}
      {{- template "nginx-s3-gateway.envoy-volumes" . }}
      {{- template "nginx-s3-gateway.opa-volumes" . }}
      {{- end}}
