exporter = "otlp"
processor = "batch"

[exporters.otlp]
# Alternatively the OTEL_EXPORTER_OTLP_ENDPOINT environment variable can also be used.
host = "localhost"
port = 4317
# Optional: enable SSL, for endpoints that support it
# use_ssl = true
# Optional: set a filesystem path to a pem file to be used for SSL encryption
# (when use_ssl = true)
# ssl_cert_path = "/path/to/cert.pem"

[processors.batch]
max_queue_size = 2048
schedule_delay_millis = 5000
max_export_batch_size = 512

[service]
#name = "nginx-proxy" # Opentelemetry resource name
name = "${OTEL_SERVICE_NAME}"

[sampler]
name = "${OTEL_TRACES_SAMPELR}" # AlwaysOn, AlwaysOff, TraceIdRatioBased
ratio = "${OTEL_TRACES_SAMPLER_RATIO}"
parent_based = "${OTEL_TRACES_SAMPLER_PARENT_BASED}"
