{{- if .Values.nginx.enabled -}}
{{- $chartName := include "nginx.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
  labels:
    app: {{ .Release.Name }}-{{ $chartName }}
    component: nginx-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  NGINX_DEFAULT_CONFIG: {{ tpl (.Files.Get "config/default.conf") . | quote }}
  NGINX_ROOT_CONFIG: {{ tpl (.Files.Get "config/nginx_root.conf") . | quote }}
  NGINX_LOG_FORMAT: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
{{- end }}
