apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-base-configmap" (include "nginx.fullname" .) }}
data:
  default.conf: {{ tpl (.Files.Get "config/default.conf") . | quote }}
  nginx.conf: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
  log_format.conf: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
