{{- $releaseName := .Release.Name -}}
{{- $chartName := include "nginx.name" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- if and (.Values.enabled) (.Values.ingress.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  {{ include "nginx.ingress.annotations" . }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ .Values.nginx.port }}
    host: {{ .Values.ingress.host | quote }}
{{- end -}}