{{- $chartName := include "nginx.name" . -}}
{{- $cloudProviderFlavor := include "nginx.cloudProviderFlavor" . -}}
{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ printf "%s-route" (include "nginx.fullname" .) }}
  annotations:
    {{- if .Values.route.rewriteTarget }}
    haproxy.router.openshift.io/rewrite-target: {{ .Values.route.rewriteTarget }}
    {{- end }}
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.durationSeconds }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  path:  {{ .Values.route.path | default "/" }}
  port:
    targetPort: nginx
  to:
    kind: Service
    name: {{ printf "%s-service" (include "nginx.fullname" .) }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | quote }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | quote }}
    {{- if .Values.route.tls.useCerts }}
    certificate: {{ .Values.route.tls.certificate | quote }}
    key: {{ .Values.route.tls.key | quote }}
    caCertificate: {{ .Values.route.tls.caCertificate | quote }}
    {{- end }}
  {{- end -}}
{{- end -}}
