
{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "nginx.name" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $cloudProviderFlavor := include "nginx.cloudProviderFlavor" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: nginx-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  # In case cloudProavider=azure
  {{- if eq $cloudProviderFlavor "azure" }}
  type: ClusterIP
  {{- end }}
  # In case cloudProvider=minikube
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.targetPort }}
      protocol: TCP
      name: nginx
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nginx.nodePort }}
      {{- end }}
      {{- if .Values.prometheusExporter.enabled }}
    - port: {{ .Values.prometheusExporter.targetPort }}
      targetPort: {{ .Values.prometheusExporter.targetPort }}
      protocol: TCP
      name: prometheus-exporter
      {{- end }}
  selector:
    app: {{ $releaseName }}-{{ $chartName }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-nginx
{{- end }}
