services:
  nginx-s3-gateway:
    build: ../
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./redis-get-key.lua:/etc/nginx/lua/redis-get-key.lua:ro
      - ./redis-set-key.lua:/etc/nginx/lua/redis-set-key.lua:ro
  redis:
    image: redis:alpine3.19
    ports:
      - 6379:6379
  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=s3-redis
    command: server /data --console-address ":9001"

  # Optional: Sets a default bucket and object in minio
  createBucket:
    image: minio/mc:RELEASE.2023-12-07T22-13-17Z.fips
    volumes:
      - ./minioData:/mnt/minioData:ro
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/s3-redis;
      /usr/bin/mc anonymous set public myminio/s3-redis;
      /usr/bin/mc cp --recursive mnt/minioData/ myminio/s3-redis/;
      "
