services:
  nginx-s3-gateway:
    build: ../
    environment:
      - S3_BUCKET_NAME=s3-redis
      - S3_SERVER=minio
      - S3_SERVER_PORT=9000
      - S3_SERVER_PROTO=http
      - S3_REGION=us-east-1
      - S3_STYLE=path
      - ALLOW_DIRECTORY_LIST=true
      - AWS_SIGS_VERSION=4
      - AWS_ACCESS_KEY_ID=s3-user
      - AWS_SECRET_ACCESS_KEY=s3-password
      - CORS_ENABLED=true
      - NGINX_WORKER_PROCESSES=4
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SKIP_CACHE=0
      - REDIS_CACHE_EXPIRATION_TIME=1000
      - REDIS_CONNECT_TIMEOUT=1000
      - REDIS_SEND_TIMEOUT=1000
      - REDIS_READ_TIMEOUT=1000
      - REDIS_MAX_IDLE_TIMEOUT=10000
      - REDIS_POOL_SIZE=100
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./redis-get-key.lua:/etc/nginx/lua/redis-get-key.lua:ro
      - ./redis-set-key.lua:/etc/nginx/lua/redis-set-key.lua:ro
  redis:
    image: redis
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=s3-user
      - MINIO_ROOT_PASSWORD=s3-password
      - MINIO_DEFAULT_BUCKETS=s3-redis
    command: server /data --console-address ":9001"

  # Optional: Sets a default bucket in minio
  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 s3-user s3-password;
      /usr/bin/mc mb myminio/s3-redis;
      /usr/bin/mc policy set public myminio/s3-redis;
      exit 0;
      "
