name: PR Checks

on: pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v9
        env:
          VALIDATE_ALL_CODEBASE: >-
            ${{
              github.event_name == 'push' &&
              github.ref == 'refs/heads/main'
            }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Upload MegaLinter artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        if: success() || failure()
        with:
          name: MegaLinter reports
          include-hidden-files: 'true'
          path: |
            megalinter-reports
            mega-linter.log

  validate-ownership:
    name: Validate Ownership
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Validate Ownership
        run: |
          MISSING=0

          # Ensure the images directory exists before running find
          if [ ! -d "images" ]; then
            echo "Error: 'images' directory not found."
            exit 1
          fi

          # List all directories inside 'images', excluding hidden directories
          for dir in $(find images -mindepth 1 -maxdepth 1 -type d -not -name '.*' | sed 's|images/||'); do
            # Check if directory exists in ownership.json keys
            if ! jq -e ".\"$dir\"" ownership.json > /dev/null; then
              echo "Error: Component '$dir' is missing from ownership.json"
              MISSING=1
            fi
          done

          if [[ $MISSING -eq 1 ]]; then
            exit 1
          fi
          echo "All components found in ownership.json"
