name: PR Checks

on: pull_request

permissions: read-all

jobs:
  mega-lint:
    name: Code Quality (MegaLinter)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install TS Project dependencies
        shell: bash
        run: npm ci
        working-directory: .

      - name: Cache MegaLinter Docker image
        id: cache-megalinter
        uses: actions/cache@v5
        with:
          path: /tmp/megalinter-image.tar
          key: megalinter-image-v9

      - name: Load MegaLinter Image
        if: steps.cache-megalinter.outputs.cache-hit == 'true'
        run: docker load -i /tmp/megalinter-image.tar || true

      - name: Lint Code (MegaLinter)
        run: npm run lint

      - name: Save MegaLinter Image
        if: ${{ always() && steps.cache-megalinter.outputs.cache-hit != 'true' }}
        run: docker save ghcr.io/oxsecurity/megalinter:v9 -o /tmp/megalinter-image.tar

  validate-ownership:
    name: Validate Ownership
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Validate Ownership
        run: |
          MISSING=0

          # Ensure the images directory exists before running find
          if [ ! -d "images" ]; then
            echo "Error: 'images' directory not found."
            exit 1
          fi

          # List all directories inside 'images', excluding hidden directories
          for dir in $(find images -mindepth 1 -maxdepth 1 -type d -not -name '.*' | sed 's|images/||'); do
            # Check if directory exists in ownership.json keys
            if ! jq -e ".\"$dir\"" ownership.json > /dev/null; then
              echo "Error: Component '$dir' is missing from ownership.json"
              MISSING=1
            fi
          done

          if [[ $MISSING -eq 1 ]]; then
            exit 1
          fi
          echo "All components found in ownership.json"
